### ISSUE TITLE
File Crashes my Xcode

### ISSUE THREAD

**Issue by jkiley129** [learn-co-curriculum/objc-interpolate#2]
Everytime I try to open the project file for this code along my Xcode crashes. I am on the new version 7.0 if that makes any difference

**Comment by AnnJohn** [comment]
Hi @StoneCloud129 thanks for raising this issue, and sorry to hear about the problem. 

@markedwardmurray could you look at this and see whether it's an engineering issue? Thanks

**Comment by markedwardmurray** [comment]
It's a bug in Xcode when opening projects created with the liftoff template which we use to generate the lab projects: https://github.com/CocoaPods/CocoaPods/issues/4150

We're looking into a resolution for it, but for now the best thing for you to do is revert to Xcode 6.4. You can download the old dmg from Apple here: https://developer.apple.com/downloads/

**Comment by markedwardmurray** [comment]
@AnnJohn Tim pushed a fix for all the affected labs he could find. fe7201f3c1a680f1b763e85e029e9842c5630432

@StoneCloud129 this should now work in Xcode 7.0
